### ISSUE TITLE
@modern-js/utils 依赖版本升级

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/codesmith#79]
目前 codesmith v2 中仍然依赖了 @modern-js/utils v1，导致 modern.js v2 项目里会同时安装 @modern-js/utils v1 和 v2:

![image](https://user-images.githubusercontent.com/7237365/211189290-11279105-a601-457c-a8cc-5a5333e04231.png)

**Comment by chenjiahan** [comment]
@caohuilin 看起来 `@modern-js/codesmith-formily` 还依赖了 utils v1 版本

https://github.com/web-infra-dev/codesmith/blob/main/packages/formily/package.json#L34

**Comment by caohuilin** [comment]
https://github.com/web-infra-dev/codesmith/pull/100
